package com.bit45.movietrack.data.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "movie")
data class Movie(

    //Not autogenerated because will be provided by the API
    @PrimaryKey
    val id: Int,

    val name: String,

    val image: String,

    @ColumnInfo(name = "is_watched")
    val isWatched: Boolean,

)