package com.bit45.movietrack.model.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.squareup.moshi.Json

@Entity(tableName = "movie")
data class Movie(

    //Not autogenerated because will be provided by the API
    @PrimaryKey
    var id: Int,

    @Json(name = "title") var name: String,

    @Json(name = "poster_path") var image: String?,

    @ColumnInfo(name = "is_watched")
    @Transient var isWatched: Boolean = false

)