package com.bit45.movietrack.model.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "movie")
data class Movie(

    //Not autogenerated because will be provided by the API
    @PrimaryKey
    var id: Int,

    var name: String,

    var image: String,

    @ColumnInfo(name = "is_watched")
    var isWatched: Boolean,

)